### ISSUE TITLE
Notification Config

### ISSUE THREAD

**Issue by rossicler** [fga-eps-mds/2020.1-stay-safe-front-end#116]
## Issue Description
Create a screen that list notifications configs
Create a switch to disable or enable the notification of new occurrences near to favorite locations

## How it will be validated
To validate the issue the following tests will be done:

- The reviewer will enter the config screen and open the notifications screen, then enable the notification of new occurrences near to favorite locations.

If the tests are successful, the issue will be considered ready.

## Tasks:
- [ ] Create the notification config screen.
- [ ] Create the switch to enable/disable the notification of new occurrences near to favorite locations.

**Comment by tsrrodrigues** [comment]
Since there is not more than one notification, because the backend uses only one attribute to check if the user want to receive notification or not, what about to do just a switch in the settings screen on notification button? @rossicler @renan601 @silvasara

**Comment by silvasara** [comment]
@tsrrodrigues Yes, It can be just a switch on the notification button in the settings screen
